### ISSUE TITLE
Add Language English

### ISSUE THREAD

**Issue by Choirrulloh** [AlanMartines/mywhatsapp-api-node-venom#1]
Hi Alan,

Thank you the program really helped me, can you add documentation in English?

**Comment by AlanMartines** [comment]
In the future I intend to assemble a very detailed documentation in Portuguese and English, at the moment the focus is being on the development of the api same ...

**Comment by Choirrulloh** [comment]
Hi Alan,

Thanks for response,

Okay, i wait.
